alias saud='sudo apt update'
alias saug='sudo apt upgrade'
alias r='ranger'
alias sr='sudo ranger'
alias v='vim'
alias sv='sudo vim'
alias clima='curl wttr.in'
alias cfv='vim ~/.vim_runtime/my_configs.vim'
alias cfi3='vim ~/.config/i3/config'
alias cfb='vim ~/.bashrc'
alias cfba='vim ~/.bash_aliases'
alias dotfiles='/usr/bin/git --git-dir=/home/sergio/dotfiles_git/ --work-tree=/home/sergio'
