#!/usr/bin/env bash
# Script finds all *.webm files in current folder and subfolders and converts it to mp3 using ffmpeg
find . -type f -iname "*.webm" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -ab 128k -ar 44100 -y "${FILE%.webm}.mp3";' _ '{}' \;
